version: '3'

services:
  db_postqresql:
    image: postgres:latest
    container_name: db_postqresql
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - DATABASE_HOST=${DB_HOST}
      - PGDATA=${DATA}
    restart: always
